apiVersion: apps/v1
kind: Deployment 
metadata:
  name: zomato-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      container:
        name: zomata-clone
        image: mukeshr29/zomato-clone
        ports:
          containerPort: 3000